### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by singpolyma** [sledorze/monax#11]
`import com.mindrocks.Monad.dO => dO;` causes:

```
Unexpected =>
```

**Comment by sledorze** [comment]
Thanks, readme fixed.

**Comment by singpolyma** [comment]
Now I get `./Main.hx:1: characters 7-26 : Class not found : com.mindrocks.Monad` -- if I fix the import to the full package name I then get `Monad.hx:82: characters 30-78 : Invalid field access : split`

**Comment by sledorze** [comment]
Sorry I was answering from the phone.
Can you post a small code reproducing the problem?
Thanks

On Mon, Feb 24, 2014 at 4:13 PM, Stephen Paul Weber <
notifications@github.com> wrote:

> Now I get ./Main.hx:1: characters 7-26 : Class not found :
> com.mindrocks.Monad -- if I fix the import to the full package name I
> then get Monad.hx:82: characters 30-78 : Invalid field access : split
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/sledorze/monax/issues/11#issuecomment-35895405
> .

## 

Stéphane Le Dorze

http://lambdabrella.blogspot.com/
http://www.linkedin.com/in/stephaneledorze
http://twitter.com/stephaneledorzehttps://twitter.com/#!/stephaneledorze/status/74020060125077504

Tel: +33 (0) 6 08  76 70 15

**Comment by singpolyma** [comment]
```
import com.mindrocks.monads.Monad.dO in dO;

class SomeClass {
    var x:Null<Int> = dO({
      value <= return 55;
      value1 <= return value * 2;
      return value1 + value;
    });
}
```

**Comment by sledorze** [comment]
Ok, I've pushed some fixes and better error reporting.
Monad instance inference requires the first comprehension type to be known (no return), otherwise, one need to explicitely state the Monad instance type (NullM.dO).
In addition, NullM has another restriction; no inference is provided as Null<T> overlaps with too much types.
Hope the error messages will help.

**Comment by singpolyma** [comment]
> Monad instance inference requires the first comprehension type to be known (no return)

Should probably not use return on the first one in the example in the readme, then :)

**Comment by singpolyma** [comment]
The new error messages are nice.  I'm trying this now:

```
import com.mindrocks.monads.Monad.dO in dO;
import haxe.ds.Option;
using com.mindrocks.monads.instances.Prelude.OptionM;

class SomeClass {
   function hello() {
      var x = dO({
         value <= Some(55);
         value1 <= return value * 2;
         return value1 + value;
       });
   }
}
```

And I get:

```
./Main.hx:8: lines 8-12 : Too many arguments
./Main.hx:8: lines 8-12 : Function 'dO' requires arguments : body
```

**Comment by sledorze** [comment]
Please have a look to the example; I've bind it to 'Do' instead of 'dO' and it works.
Will look where's the problem exactly with 'dO' (as it used to work..).

**Comment by sledorze** [comment]
Sorry it looked so broken.. looks like it got a bit rotten with time. Hope it's back on its feet now :)

**Comment by singpolyma** [comment]
Awesome.  Thanks!

**Comment by sledorze** [comment]
New version 1.5.1 released on haxelib with these fixes.
