### ISSUE TITLE
Can a monad have a type parameter

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [sledorze/monax#12]
Hi,

I have already asked a [related question](https://groups.google.com/forum/?hl=en#!topic/haxelang/uj0P7nIzlek) in the haxe mailing list.

I would like to write a monad for a [Surprise](https://github.com/haxetink/tink_core#surprise) from [tink_core](https://github.com/haxetink/tink_core). I have done this assuming "Failure=String" like this:

```
  inline public static function flatMap<T, U>(x : Surprise<T,String>, f : T -> (Surprise<U,String>)) : Surprise<U,String> {
    return x.flatMap(function(t) {
      return switch(t) {
        case Failure(s):
          Future.sync(Failure(s));
        case Success(v):
          f(v);
        }
    });
  }
```

So it gets the first surprise (x), and than executes f only if the result is a success. Otherwise it directly returns the failure.

Now I want to generalize this and make a "MonadSurprise<F>" where F denotes the type of the Failure.

But I am failing because I cannot write:

```
public static function monad<T>(f : Surprise<T, F>) return
MonadSurprise<F>;
```

According to the [thread]() I already started it might be ok if "monad" just returns a instance of "MonadSurprise<F>" and all "flatMap" and similar are made non-static.

But I do not know how to write the "dO" function. Maybe like this:

```
  macro public static function dO<F2>(body : Expr) return // the function to trigger the Monad macro.
    Monad._dO("monads.MonadSurprise<" + Type.getClassName(F2) + ">", body, Context);
```

But, when calling it like this:

```
 MonadSurprise.dO<Error>({
    ...
});
```

I get:

```
Error:(42, 4) Macro functions must be called immediately
```

**Comment by back2dos** [comment]
That syntax won't work, because what the parser sees is `MonadSurprise.dO < (Error > ({ ... }))` which of course is non-sense. The typer sees the comparison and proceed to type the LHS, to discover it is a field access to a macro (without calling it) and thus gives you the error you are getting.

Instead of determining the type parameter though, you might instead consider this:

```
  inline public static function flatMap<T, U, E>(x : Surprise<T,E>, f : T -> (Surprise<U,E>)) : Surprise<U,String> {
    return x.flatMap(function(t) {
      return switch(t) {
        case Failure(s):
          Future.sync(Failure(s));
        case Success(v):
          f(v);
        }
    });
  }
```

So the error type is thus not really "part of the monad". The compiler will simply determine whether the error types unify and give you an error otherwise.

**Comment by sledorze** [comment]
I think @back2dos explained it quite well :)

**Comment by back2dos** [comment]
@sledorze You are assuming the code I posted actually works :D

**Comment by sledorze** [comment]
No it does not work (there's at least a wrong String param) but the
explanation is correct.

On Wed, Jul 8, 2015 at 7:15 AM, Juraj Kirchheim notifications@github.com
wrote:

> @sledorze https://github.com/sledorze You are assuming the code I
> posted actually works :D
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sledorze/monax/issues/12#issuecomment-119435622.

## 

Stéphane Le Dorze

http://lambdabrella.blogspot.com/
http://www.linkedin.com/in/stephaneledorze
http://twitter.com/stephaneledorze
https://twitter.com/#!/stephaneledorze/status/74020060125077504

Tel: +33 (0) 6 08  76 70 15
