### ISSUE TITLE
nodejs monad is called two time with haxe timer delay

### ISSUE THREAD

**Issue by francescoagati** [sledorze/monax#2]
Hi,
i have try to modify the nodejs monad in test example for simulate async function with haxe timer delay. It work fine but the function with the trace is calling two times.

Here the code. I've tested the compiled js on safari browser

```
import com.mindrocks.monads.instances.Prelude;

import com.mindrocks.monads.Monad;
import com.mindrocks.monads.instances.NodeJs;


using com.mindrocks.monads.instances.Prelude;


class Obj {
  var name : String;
  public function new(name : String) {    
    this.name = name;
  }
}

class Collection {
  var objs : Array<Obj>;
  public function new() { 
    objs = [new Obj("a"), new Obj("b")];
  }
  public function all(name : Dynamic, cb : Error -> Array<Obj> -> Void) {    
    // cb("Aieeeuu!!", null);
    haxe.Timer.delay(function() {
      cb(null, objs);
    }, 1000);

  }
}

class DB {
  var coll : Collection;
  public function new() {
    coll = new Collection();
  }
  public function collection(name : String, cb : Error -> Collection -> Void) {

    haxe.Timer.delay(function() {
      cb(null, coll);
    }, 1000);

  }
}


class Main {

  public static function main(){

    var db = new DB();    
     var res5 : String = "";

     NodeM.dO({
       coll <= db.collection("avatars", _);
       avatars <= coll.all("ssss", _);
       ret(avatars.length);
     })(function (err, res) trace(res));


  }

}





```

**Comment by sledorze** [comment]
Works (tested in Chrome) (?!?)

You got to make sense of it..
do you have the latest monax on haxelib?

Stephane

2012/1/24 francesco agati <
reply@reply.github.com

> Hi,
> i have try to modify the nodejs monad in test example for simulate async
> function with haxe timer delay. It work fine but the function with the
> trace is calling two times.
> 
> Here the code. I've tested the compiled js on safari browser
> 
> ```
> import com.mindrocks.monads.instances.Prelude;
> 
> import com.mindrocks.monads.Monad;
> import com.mindrocks.monads.instances.NodeJs;
> 
> 
> using com.mindrocks.monads.instances.Prelude;
> 
> 
> class Obj {
>  var name : String;
>  public function new(name : String) {
>    this.name = name;
>  }
> }
> 
> class Collection {
>  var objs : Array<Obj>;
>  public function new() {
>    objs = [new Obj("a"), new Obj("b")];
>  }
>  public function all(name : Dynamic, cb : Error -> Array<Obj> -> Void) {
>    // cb("Aieeeuu!!", null);
>    haxe.Timer.delay(function() {
>      cb(null, objs);
>    }, 1000);
> 
>  }
> }
> 
> class DB {
>  var coll : Collection;
>  public function new() {
>    coll = new Collection();
>  }
>  public function collection(name : String, cb : Error -> Collection ->
> Void) {
> 
>    haxe.Timer.delay(function() {
>      cb(null, coll);
>    }, 1000);
> 
>  }
> }
> 
> 
> class Main {
> 
>  public static function main(){
> 
>    var db = new DB();
>     var res5 : String = "";
> 
>     NodeM.dO({
>       coll <= db.collection("avatars", _);
>       avatars <= coll.all("ssss", _);
>       ret(avatars.length);
>     })(function (err, res) trace(res));
> 
> 
>  }
> 
> }
> 
> 
> 
> 
> 
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sledorze/monax/issues/2

## 

Stphane Le Dorze

http://lambdabrella.blogspot.com/
http://www.linkedin.com/in/stephaneledorze
http://twitter.com/stephaneledorzehttps://twitter.com/#!/stephaneledorze/status/74020060125077504

Tel: +33 (0) 6 08  76 70 15

**Comment by francescoagati** [comment]
I've tried directly download the repository github

and i have like result also on chrome:

Main.hx:57: 2
Main.hx:57: 2

**Comment by francescoagati** [comment]
i have create the example i do in this repository:

https://github.com/francescoagati/monax_example_double_twice

compile Test.hxml and open index.html page

**Comment by sledorze** [comment]
Have you tested against the haxelib version????

2012/1/24 francesco agati <
reply@reply.github.com

> I've tried directly download the repository github
> 
> and i have like result also on chrome:
> 
> Main.hx:57: 2
> Main.hx:57: 2
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sledorze/monax/issues/2#issuecomment-3632298

## 

Stphane Le Dorze

http://lambdabrella.blogspot.com/
http://www.linkedin.com/in/stephaneledorze
http://twitter.com/stephaneledorzehttps://twitter.com/#!/stephaneledorze/status/74020060125077504

Tel: +33 (0) 6 08  76 70 15

**Comment by francescoagati** [comment]
no i have take directly the repository github https://github.com/sledorze/monax/. can be this the problem?

**Comment by sledorze** [comment]
Shame on you for the forthcoming thousand years!!! :)

<html>

```
<div id="haxe:trace"></div>
```

   <script src="main.js"></script>             <<<<<<<<<<< Implicitely
executes Main.main()
   <script>
    Main.main();                                       <<<<<<<<<<<
Explicitely executes Main.main() a second time..
   </script>
</html>

:)
Stephane

2012/1/24 francesco agati <
reply@reply.github.com

> no i have take directly the repository github
> https://github.com/sledorze/monax/. can be this the problem?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sledorze/monax/issues/2#issuecomment-3632661

## 

Stphane Le Dorze

http://lambdabrella.blogspot.com/
http://www.linkedin.com/in/stephaneledorze
http://twitter.com/stephaneledorzehttps://twitter.com/#!/stephaneledorze/status/74020060125077504

Tel: +33 (0) 6 08  76 70 15

**Comment by francescoagati** [comment]
ops...... sorry for the mistake :-) i haven't see  pardon :-(
